/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "api.attachments.download": [
        {
            "name": "attachment",
            "required": true,
            "binding": "id"
        }
    ],
    "locale.set": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "admin.register": [],
    "admin.": [],
    "admin.login": [],
    "admin.password.request": [],
    "admin.password.email": [],
    "admin.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "admin.password.store": [],
    "admin.dashboard": [],
    "admin.profile": [],
    "admin.profile.update": [],
    "admin.profile.update.post": [],
    "admin.governorates.index": [],
    "admin.governorates.create": [],
    "admin.governorates.store": [],
    "admin.governorates.show": [
        {
            "name": "governorate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.governorates.edit": [
        {
            "name": "governorate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.governorates.update": [
        {
            "name": "governorate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.governorates.destroy": [
        {
            "name": "governorate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.governorates.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.governorates.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.districts.index": [],
    "admin.districts.create": [],
    "admin.districts.store": [],
    "admin.districts.show": [
        {
            "name": "district",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.districts.edit": [
        {
            "name": "district",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.districts.update": [
        {
            "name": "district",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.districts.destroy": [
        {
            "name": "district",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.districts.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.districts.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.areas.index": [],
    "admin.areas.create": [],
    "admin.areas.store": [],
    "admin.areas.show": [
        {
            "name": "area",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.areas.edit": [
        {
            "name": "area",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.areas.update": [
        {
            "name": "area",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.areas.destroy": [
        {
            "name": "area",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.areas.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.areas.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.certificates.document.view": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificates.document.download": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificates.index": [],
    "admin.certificates.create": [],
    "admin.certificates.store": [],
    "admin.certificates.show": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificates.edit": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificates.update": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificates.destroy": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.index": [],
    "admin.tags.create": [],
    "admin.tags.store": [],
    "admin.tags.show": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.edit": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.update": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.destroy": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultation-types.index": [],
    "admin.consultation-types.create": [],
    "admin.consultation-types.store": [],
    "admin.consultation-types.show": [
        {
            "name": "consultation_type",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultation-types.edit": [
        {
            "name": "consultation_type",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultation-types.update": [
        {
            "name": "consultation_type",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultation-types.destroy": [
        {
            "name": "consultation_type",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultation-types.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultation-types.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.categories.index": [],
    "admin.categories.create": [],
    "admin.categories.store": [],
    "admin.categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.categories.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.categories.uploadIcon": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.categories.removeIcon": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultants.index": [],
    "admin.consultants.create": [],
    "admin.consultants.store": [],
    "admin.consultants.show": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.edit": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.update": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.destroy": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultants.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultants.working-hours.replace": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.holidays.replace": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultants.experiences.replace": [
        {
            "name": "consultant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultant-services.index": [],
    "admin.consultant-services.create": [],
    "admin.consultant-services.store": [],
    "admin.consultant-services.show": [
        {
            "name": "consultant_service",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultant-services.edit": [
        {
            "name": "consultant_service",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultant-services.update": [
        {
            "name": "consultant_service",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultant-services.destroy": [
        {
            "name": "consultant_service",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.consultant-services.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.consultant-services.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.bookings.available-slots": [],
    "admin.bookings.index": [],
    "admin.bookings.create": [],
    "admin.bookings.store": [],
    "admin.bookings.show": [
        {
            "name": "booking",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.bookings.edit": [
        {
            "name": "booking",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.bookings.update": [
        {
            "name": "booking",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.bookings.destroy": [
        {
            "name": "booking",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.bookings.cancel": [
        {
            "name": "booking",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.index": [],
    "admin.admins.create": [],
    "admin.admins.store": [],
    "admin.admins.show": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.edit": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.update": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.destroy": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.activate": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.admins.deactivate": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.index": [],
    "admin.roles.create": [],
    "admin.roles.store": [],
    "admin.roles.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.deactivate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissions.index": [],
    "admin.activitylogs.index": [],
    "admin.activitylogs.show": [
        {
            "name": "activitylog",
            "required": true
        }
    ],
    "admin.verification.notice": [],
    "admin.verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "admin.verification.send": [],
    "admin.password.confirm": [],
    "admin.password.update": [],
    "admin.logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
